name: build and deploy code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v4
      - name: install python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install poetry
        run: pip install poetry==1.6.1
      - name: installing dependencies
        run: poetry install